services:
  - type: web
    name: snake-area
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-area-db
          property: connectionString
    autoDeployTrigger: commit

databases:
  - name: snake-area-db
    plan: free
    databaseName: snake_area
    user: snake_area